[job-exec "backup-minio"]
schedule  = 0 2 * * *
container = bizfirst-storage-server-backup-minio
command   = /usr/local/bin/backup-minio.sh

# docker exec bizfirst-storage-server-backup-minio /usr/local/bin/backup-minio.sh

[job-exec "backup-sqlserver"]
schedule  = 10 2 * * *
container = bizfirst-storage-server-backup-sqlserver
command   = /usr/local/bin/backup-sqlserver.sh

# docker exec bizfirst-storage-server-backup-sqlserver /usr/local/bin/backup-sqlserver.sh

[job-exec "backup-postgresql"]
schedule  = 20 2 * * *
container = bizfirst-storage-server-backup-postgresql
command   = /usr/local/bin/backup-postgres.sh

# docker exec bizfirst-storage-server-backup-postgresql /usr/local/bin/backup-postgres.sh

