global:
  scrape_interval: 15s

scrape_configs:
  - job_name: bizfirst-primary
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYml6Zmlyc3QiLCJleHAiOjQ5MzgyMzYyMTJ9.qpmWIMvq8bAA0A1qQqCMmYuyACKe_4KJvbD3Qjsx9HCMg9Txoy2N1MsHFCjW_CoqOzG0iixULJf7O9xy7HEY4Q
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['bizfirst-primary:9000']

  - job_name: bizfirst-hotstandby
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYml6Zmlyc3QiLCJleHAiOjQ5MzgyMzY4NzB9.ImlvhykGTNgYSiHaOin1ps0J2aYsGdNuCsqaGZhnr2GuBhh49n3TyR-KBQmzg0jTj9JMkOoT_p652swAWshkBg
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["bizfirst-hotstandby:9000"]

  - job_name: bizfirst-archival
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYml6Zmlyc3QiLCJleHAiOjQ5MzgyMzY4NzB9.ImlvhykGTNgYSiHaOin1ps0J2aYsGdNuCsqaGZhnr2GuBhh49n3TyR-KBQmzg0jTj9JMkOoT_p652swAWshkBg
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["bizfirst-archival:9000"]

  - job_name: bizfirst-compliance
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYml6Zmlyc3QiLCJleHAiOjQ5MzgyMzY4NzB9.ImlvhykGTNgYSiHaOin1ps0J2aYsGdNuCsqaGZhnr2GuBhh49n3TyR-KBQmzg0jTj9JMkOoT_p652swAWshkBg    
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["bizfirst-compliance:9000"]

  - job_name: bizfirst-pitr
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYml6Zmlyc3QiLCJleHAiOjQ5MzgyMzY4NzB9.ImlvhykGTNgYSiHaOin1ps0J2aYsGdNuCsqaGZhnr2GuBhh49n3TyR-KBQmzg0jTj9JMkOoT_p652swAWshkBg
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["bizfirst-pitr:9000"]
